// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan():Promise<void>;

export function StartScan(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<string>;

export function StartScanList(arg1:string,arg2:Array<number>,arg3:number,arg4:number):Promise<string>;
