// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function StartScan(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3, arg4, arg5);
}

export function StartScanList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartScanList'](arg1, arg2, arg3, arg4);
}
